### ISSUE TITLE
does not appear to be a way to get to the showcase page from iiif.io

### ISSUE THREAD

**Issue by mejackreed** [IIIF/showcase.iiif.io#28]
Upon a quick review, there does not seem to be an easy way to get to the showcase from iiif.io 

Is this by design? To me it seems it should be at least linked from "Apps & Demos"

**Comment by azaroth42** [comment]
Hi Jack! It's by design, or at least by redesign ... It will be linked from the header in the reworked site, which I'm building out slowly at: http://redesign.iiif.io/ (via the redesign branch in the IIIF/iiif.io repo)

**Comment by mejackreed** [comment]
Ah great thanks!
