### ISSUE TITLE
Mirador showcase is broken

### ISSUE THREAD

**Issue by jcoyne** [IIIF/showcase.iiif.io#44]
This URL http://showcase.iiif.io/showcase/mirador-viewer/

points at a non-existent server `sul-reader-test.stanford.edu`
Probably on this line https://github.com/IIIF/showcase.iiif.io/blob/25083771f1f8639745d6f42bd1b7e6ef5c784228/source/showcase/mirador-viewer.html#L11

cc @snydman @mejackreed

**Comment by glenrobson** [comment]
Fixed now thanks to https://github.com/IIIF/showcase.iiif.io/pull/46
