### ISSUE TITLE
https replacement for the YBCA viewer

### ISSUE THREAD

**Issue by glenrobson** [IIIF/showcase.iiif.io#50]
Is there a replacement https link for:

http://collections.britishart.yale.edu/zoom/index.html?image=c0b22208-1eab-4b5e-8bc2-a18390f003b4&credit=Johan%20Joseph%20Zoffany,%201733%E2%80%931810,%20German,%20active%20in%20Britain%20%28from%201760%29,%20The%20Gore%20Family%20with%20George,%20third%20Earl%20Cowper,%20ca.%201775,%20Oil%20on%20canvas,%20Yale%20Center%20for%20British%20Art,%20Paul%20Mellon%20Collection

which is currently located at:

http://showcase.iiif.io/showcase/ycba/

cc @mikeapp

**Comment by mikeapp** [comment]
I'm working on that, it should be available in the next week or so.

**Comment by glenrobson** [comment]
Great thanks Mike

**Comment by mikeapp** [comment]
This now redirects to https - go ahead and update the link.

**Comment by glenrobson** [comment]
Added to https branch.
