### ISSUE TITLE
https replacement for SAT Taishōzō Image DB

### ISSUE THREAD

**Issue by glenrobson** [IIIF/showcase.iiif.io#52]
Is there a https replacement for the following link:

http://dzkimgs.l.u-tokyo.ac.jp/SATi/images.php?alang=en

found in:

http://showcase.iiif.io/showcase/satdb/

cc: @knagasaki

**Comment by kiyonoriNagasaki** [comment]
Thank you for notifying on this! I changed the URL to https.

**Comment by glenrobson** [comment]
Thanks for your help and quick response I've deployed that pull request now.
